/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accidents: typeof import('./src/components/Accidents.vue')['default']
    Barchart: typeof import('./src/components/charts/Barchart.vue')['default']
    BoxFactors: typeof import('./src/components/BoxFactors.vue')['default']
    BoxInfo: typeof import('./src/components/charts/BoxInfo.vue')['default']
    DropDownListAccidentGeneral: typeof import('./src/components/charts/DropDownListAccidentGeneral.vue')['default']
    DropDownListLineChart: typeof import('./src/components/charts/DropDownListLineChart.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Linechart: typeof import('./src/components/charts/Linechart.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
